import type { PenPreset } from "@/types/configurator";

export const PEN_PRESETS: PenPreset[] = [
  // ========== ZEUS PRESETS ==========
  {
    id: "zeus-golden-executive",
    name: "Zeus Golden Executive",
    model: "zeus",
    description: "Bold black lacquer with 18K gold accents. The ultimate power statement.",
    basePrice: 2499,
    featured: true,
    config: {
      model: "zeus",
      bodyMaterial: "lacquer",
      bodyColor: "#1a1a1a",
      bodyPattern: "solid",
      bodyFinish: "glossy",
      nibSize: "B",
      nibMaterial: "gold-18k",
      nibStyle: "standard",
      trimFinish: "yellow-gold",
      clipStyle: "classic",
      engraving: {
        location: "none",
        font: "script",
        text: "",
      },
      inkColor: "midnight-black",
      handPreference: "right",
      fillingMechanism: "piston",
    },
  },
  {
    id: "zeus-platinum-elite",
    name: "Zeus Platinum Elite",
    model: "zeus",
    description: "Gunmetal titanium body with platinum trim. Modern sophistication.",
    basePrice: 2799,
    featured: true,
    config: {
      model: "zeus",
      bodyMaterial: "metal",
      bodyColor: "#2a3439",
      bodyPattern: "solid",
      bodyFinish: "satin",
      nibSize: "M",
      nibMaterial: "platinum",
      nibStyle: "standard",
      trimFinish: "platinum",
      clipStyle: "modern",
      engraving: {
        location: "none",
        font: "grotesque",
        text: "",
      },
      inkColor: "charcoal",
      handPreference: "right",
      fillingMechanism: "piston",
    },
  },
  {
    id: "zeus-ruby-monarch",
    name: "Zeus Ruby Monarch",
    model: "zeus",
    description: "Deep burgundy resin with rose gold details. Regal elegance.",
    basePrice: 1899,
    featured: false,
    config: {
      model: "zeus",
      bodyMaterial: "resin",
      bodyColor: "#800020",
      bodyPattern: "marble",
      bodyFinish: "glossy",
      nibSize: "B",
      nibMaterial: "gold-14k",
      nibStyle: "standard",
      trimFinish: "rose-gold",
      clipStyle: "classic",
      engraving: {
        location: "none",
        font: "script",
        text: "",
      },
      inkColor: "burgundy",
      handPreference: "right",
      fillingMechanism: "piston",
    },
  },

  // ========== POSEIDON PRESETS ==========
  {
    id: "poseidon-ocean-depths",
    name: "Poseidon Ocean Depths",
    model: "poseidon",
    description: "Navy blue pearl celluloid with rhodium accents. Inspired by the deep sea.",
    basePrice: 1699,
    featured: true,
    config: {
      model: "poseidon",
      bodyMaterial: "resin",
      bodyColor: "#000080",
      bodyPattern: "pearl",
      bodyFinish: "glossy",
      nibSize: "M",
      nibMaterial: "gold-14k",
      nibStyle: "standard",
      trimFinish: "rhodium",
      clipStyle: "classic",
      engraving: {
        location: "none",
        font: "script",
        text: "",
      },
      inkColor: "oxford-blue",
      handPreference: "right",
      fillingMechanism: "cartridge-converter",
    },
  },
  {
    id: "poseidon-teal-wave",
    name: "Poseidon Teal Wave",
    model: "poseidon",
    description: "Turquoise swirl with brushed steel trim. Flowing like ocean waves.",
    basePrice: 1499,
    featured: true,
    config: {
      model: "poseidon",
      bodyMaterial: "resin",
      bodyColor: "#008080",
      bodyPattern: "marble",
      bodyFinish: "satin",
      nibSize: "F",
      nibMaterial: "steel",
      nibStyle: "italic",
      trimFinish: "brushed-steel",
      clipStyle: "minimalist",
      engraving: {
        location: "none",
        font: "rounded",
        text: "",
      },
      inkColor: "turquoise",
      handPreference: "right",
      fillingMechanism: "cartridge-converter",
    },
  },
  {
    id: "poseidon-carbon-trident",
    name: "Poseidon Carbon Trident",
    model: "poseidon",
    description: "Matte carbon fiber with black chrome details. Tactical luxury.",
    basePrice: 1899,
    featured: false,
    config: {
      model: "poseidon",
      bodyMaterial: "carbon-fiber",
      bodyColor: "#1a1a1a",
      bodyPattern: "carbon-weave",
      bodyFinish: "matte",
      nibSize: "M",
      nibMaterial: "steel",
      nibStyle: "standard",
      trimFinish: "black-chrome",
      clipStyle: "modern",
      engraving: {
        location: "none",
        font: "grotesque",
        text: "",
      },
      inkColor: "midnight-black",
      handPreference: "right",
      fillingMechanism: "piston",
    },
  },

  // ========== HERA PRESETS ==========
  {
    id: "hera-pearl-goddess",
    name: "Hera Pearl Goddess",
    model: "hera",
    description: "Luminous pearl white with rose gold filigree. Divine femininity.",
    basePrice: 1399,
    featured: true,
    config: {
      model: "hera",
      bodyMaterial: "resin",
      bodyColor: "#f8f9fa",
      bodyPattern: "pearl",
      bodyFinish: "glossy",
      nibSize: "F",
      nibMaterial: "gold-14k",
      nibStyle: "italic",
      trimFinish: "rose-gold",
      clipStyle: "minimalist",
      engraving: {
        location: "none",
        font: "script",
        text: "",
      },
      inkColor: "royal-blue",
      handPreference: "right",
      fillingMechanism: "cartridge-converter",
    },
  },
  {
    id: "hera-amethyst-elegance",
    name: "Hera Amethyst Elegance",
    model: "hera",
    description: "Deep purple celluloid with platinum details. Regal sophistication.",
    basePrice: 1599,
    featured: true,
    config: {
      model: "hera",
      bodyMaterial: "resin",
      bodyColor: "#4b0082",
      bodyPattern: "marble",
      bodyFinish: "glossy",
      nibSize: "EF",
      nibMaterial: "gold-18k",
      nibStyle: "standard",
      trimFinish: "platinum",
      clipStyle: "classic",
      engraving: {
        location: "none",
        font: "serif",
        text: "",
      },
      inkColor: "purple",
      handPreference: "right",
      fillingMechanism: "cartridge-converter",
    },
  },
  {
    id: "hera-champagne-grace",
    name: "Hera Champagne Grace",
    model: "hera",
    description: "Warm champagne lacquer with yellow gold trim. Timeless beauty.",
    basePrice: 1299,
    featured: false,
    config: {
      model: "hera",
      bodyMaterial: "lacquer",
      bodyColor: "#f7e7ce",
      bodyPattern: "solid",
      bodyFinish: "glossy",
      nibSize: "F",
      nibMaterial: "gold-14k",
      nibStyle: "flex",
      trimFinish: "yellow-gold",
      clipStyle: "classic",
      engraving: {
        location: "none",
        font: "script",
        text: "",
      },
      inkColor: "amber",
      handPreference: "right",
      fillingMechanism: "piston",
    },
  },
];

// Helper functions
export const getPresetById = (id: string) => {
  return PEN_PRESETS.find((preset) => preset.id === id);
};

export const getPresetsByModel = (model: string) => {
  return PEN_PRESETS.filter((preset) => preset.model === model);
};

export const getFeaturedPresets = () => {
  return PEN_PRESETS.filter((preset) => preset.featured);
};
